compile_openblas_macos_arm64_task:
  name: Compile OpenBLAS on MacOS arm64
  alias: compile_openblas_macos_arm64
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  env:
    MACOSX_DEPLOYMENT_TARGET: "11.0"
  clone_script:
    - echo SKIP CLONE
  install_requirements_script:
    - brew install p7zip
  compile_openblas_arm64_script:
    - curl -L -o OpenBLAS-0.3.25.tar.gz https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.25/OpenBLAS-0.3.25.tar.gz
    - tar -xzf OpenBLAS-0.3.25.tar.gz
    - make -C OpenBLAS-0.3.25 TARGET=ARMV8 DYNAMIC_ARCH=1
    - make install -C OpenBLAS-0.3.25 PREFIX=${CIRRUS_WORKING_DIR}/OpenBLAS
    - 7z a OpenBLAS_macos_arm64.zip ./OpenBLAS/*
    - curl -X DELETE -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${REPO_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/daducci/AMICO/actions/variables/CIRRUS_BUILD_ID
    - curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${REPO_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/daducci/AMICO/actions/variables -d '{"name":"CIRRUS_BUILD_ID","value":"'"$CIRRUS_BUILD_ID"'"}'
  compiled_openblas_artifacts:
    path: 'OpenBLAS_macos_arm64.zip'

build_macos_arm64_wheels_task:
  name: Build MacOS arm64 wheels
  alias: build_macos_arm64_wheels
  only_if: ${CIRRUS_CHANGE_IN_REPO} != ${CIRRUS_LAST_GREEN_CHANGE} && (${CIRRUS_BRANCH} == 'master' || ${CIRRUS_BRANCH} =~ 'release/.*')
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  matrix:
    - env:
        CP: "38"
    - env:
        CP: "39"
    - env:
        CP: "310"
    - env:
        CP: "311"
  env:
    MACOSX_DEPLOYMENT_TARGET: 11.0
    PATH: ${PATH}:/opt/homebrew/opt/python@3.10/bin
    CIBW_PLATFORM: macos
    CIBW_BUILD: cp${CP}-macosx_arm64
    CIBW_ARCHS_MACOS: arm64
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
      DYLD_LIBRARY_PATH=${CIRRUS_WORKING_DIR}/OpenBLAS/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
  install_requirements_script:
    - brew install p7zip
    - brew install jq
    - brew install python@3.10
    - python3.10 -m pip install cibuildwheel==2.16.2
  download_compiled_openblas_script:
    - CIRRUS_BUILD_ID=$(curl -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${REPO_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/daducci/AMICO/actions/variables/CIRRUS_BUILD_ID | jq -r .value)
    - curl -L -o OpenBLAS.zip https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/compile_openblas_macos_arm64/compiled_openblas/OpenBLAS_macos_arm64.zip
    - 7z x OpenBLAS.zip -o"OpenBLAS"
  set_up_configuration_file_script:
    - python3.10 setup_site.py openblas openblas ${CIRRUS_WORKING_DIR}/OpenBLAS/lib ${CIRRUS_WORKING_DIR}/OpenBLAS/include
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_macos_arm64_artifacts:
    path: './wheelhouse/*.whl'

trigger_github_workflow_task:
  name: Trigger GitHub workflow
  only_if: ${CIRRUS_CHANGE_IN_REPO} != ${CIRRUS_LAST_GREEN_CHANGE} && (${CIRRUS_BRANCH} == 'master' || ${CIRRUS_BRANCH} =~ 'release/.*')
  depends_on: build_macos_arm64_wheels
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  clone_script:
    - echo SKIP CLONE
  install_requirements_script:
    - brew install jq
  trigger_script:
    - CHECK_ID_MACOS_ARM64=$(curl -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${REPO_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/daducci/AMICO/actions/variables/CHECK_ID_MACOS_ARM64 | jq -r .value)
    - curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${REPO_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/daducci/AMICO/actions/workflows/macos_arm64_wheels.yml/dispatches -d '{"ref":"'"$CIRRUS_BRANCH"'","inputs":{"cirrus_build_id":"'"$CIRRUS_BUILD_ID"'","check_id_macos_arm64":"'"$CHECK_ID_MACOS_ARM64"'"}}'
